version: '2'


services:
    logservice1:
        environment:
            - PORT=35001
        build:
            context: ./logservice
            dockerfile: Dockerfile
        container_name: logservice1
        links:
        - db
    logservice2:
        environment:
            - PORT=35002
        build:
            context: ./logservice
            dockerfile: Dockerfile
        container_name: logservice2
        links:
        - db
    logservice3:
        environment:
            - PORT=35003
        build:
            context: ./logservice
            dockerfile: Dockerfile
        container_name: logservice3
        links:
        - db
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
volumes:
    mongodb:
    mongodb_config:
